name: 'Create Hotfix 2nd PR'
description: 'Open second PR if branch is hotfix'
author: 'kibibit'
branding:
  icon: git-pull-request
  color: yellow
inputs:
  token: # change this
    required: true
    description: 'github token'
  hotfixAgainstBranch:
    required: true
    description: 1st branch (usually master\main)
  openPrAgainstBranch:
    required: true
    description: 2nd branch (usually develop)
runs:
  using: 'node12'
  main: 'dist/index.js'
