name: '@kibibit/gitflow-hotfix'
description: 'Open second PR if branch is hotfix based on gitflow rules'
author: 'kibibit'
branding:
  icon: git-pull-request
  color: yellow
inputs:
  token: # change this
    required: true
    description: github token to run the action against
  reviewerToken:
    required: false
    description: github token to use for the review approval
  hotfixAgainstBranch:
    required: true
    description: 1st branch (usually master\main)
  openPrAgainstBranch:
    required: true
    description: 2nd branch (usually develop)
  jobName:
    required: true
    description: the github workflow job name which runs this github action
  sharedLabels:
    required: false
    description: comma separated list of labels to add to BOTH PRs
  labels:
    required: false
    description: comma separated list of labels to add to the PR
  titlePrefix:
    required: false
    description: title prefix (default is [AUTO])
  checkBranchPrefix:
    required: false
    description: prefix to test branch names against (default is 'hotfix/')
runs:
  using: 'node20'
  main: 'dist/index.js'
